export const ErrorCodes = {
  // Autenticazione e autorizzazione
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  
  // Errori database
  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  
  // Errori di validazione
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_FIELD: "MISSING_FIELD",
  
  // Errori servizio email
  EMAIL_SENDING_FAILED: "EMAIL_SENDING_FAILED",
  INVALID_EMAIL: "INVALID_EMAIL",
  
  // Errori WebSocket
  WS_CONNECTION_FAILED: "WS_CONNECTION_FAILED",
  INVALID_MESSAGE_FORMAT: "INVALID_MESSAGE_FORMAT"
};